name: lesson2_10
description:

publish_to:


version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  dio: ^5.8.0+1
  provider: ^6.1.5
  flutter_screenutil: ^5.9.3
  go_router: ^16.1.0
  flutter_secure_storage: ^9.2.4
  hive: ^2.2.3
  path_provider: ^2.1.5
  hive_flutter: ^1.1.0
  build_runner: ^2.7.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  json_serializable: ^6.11.0


flutter:
  assets:
    - assets/


  uses-material-design: true



